export const BUILTIN_CAPABILITIES = Object.freeze([
  { kind: "quote", toolId: "qveris_finance.mkt_l1_rt", capability: "MKT.L1.RT", description: "实时或近实时 Level 1 行情快照", parameters: { symbol: "string" }, returns: ["price", "change", "change_percent", "timestamp", "volume", "open", "high", "low", "previous_close"] },
  { kind: "details", toolId: "qveris_finance.ref_company_profile", capability: "REF.COMPANY_PROFILE", description: "上市公司基础概况与静态资料", parameters: { symbol: "string" }, returns: ["name", "exchange", "currency", "industry", "description", "market_cap"] },
  { kind: "fundamentals", toolId: "qveris_finance.fundamentals_derived_ratios", capability: "FUNDAMENTALS.DERIVED_RATIOS", description: "估值与盈利指标快照", parameters: { symbol: "string" }, returns: ["pe_ttm", "pb_ratio", "ps_ratio_ttm", "ev_to_ebitda", "dividend_yield", "as_of_date"] },
  { kind: "series", toolId: "qveris_finance.mkt_bars_eod", capability: "MKT.BARS.EOD", description: "历史日线 OHLCV 时间序列", parameters: { symbol: "string", start_date: "string", end_date: "string" }, returns: ["date", "open", "high", "low", "close", "volume"] },
  { kind: "core_event", toolId: "qveris_finance.event_calendar_corp", capability: "EVENT.CALENDAR.CORP", description: "上市公司分红、拆股、股东会等已排期事件", parameters: { symbol: "string", event_type: "string?", start_date: "string?", end_date: "string?" }, returns: ["date", "event_type", "description", "ratio"] },
  { kind: "capital_flow", toolId: "qveris_finance.flow_large_order", capability: "FLOW.LARGE_ORDER", description: "按订单规模拆分的个股资金流", parameters: { symbol: "string", start_date: "string?", end_date: "string?" }, returns: ["date", "super_large_net", "large_net", "medium_net", "small_net", "main_net"] },
  { kind: "sentiment", toolId: "qveris_finance.news_fin_tagged", capability: "NEWS.FIN.TAGGED", description: "带主题与情绪标签的财经新闻", parameters: { symbol: "string", start_date: "string?", end_date: "string?" }, returns: ["title", "url", "published_at", "source", "summary", "sentiment_label", "sentiment_score"] },
  { kind: "market_news", toolId: "qveris_finance.news_fin_realtime", capability: "NEWS.FIN.REALTIME", description: "实时财经新闻流，可按行业或宏观关键词查询", parameters: { query: "string", category: "string?", start_date: "string?", end_date: "string?", limit: "integer?" }, returns: ["title", "summary", "source", "published_at", "url", "symbol"], coverage: "仅展示上游实际返回的新闻；关键词未命中时保持空态" },
  { kind: "index_levels", toolId: "qveris_finance.index_levels", capability: "INDEX.LEVELS", description: "海外主要股票指数实时或延迟点位", parameters: { query: "string?", symbol: "string?", market: "string?", interval: "string?" }, returns: ["symbol", "name", "price", "change", "change_percent", "timestamp"], coverage: "按 QVeris 实际覆盖返回；无点位时不显示示例数据" },
  { kind: "commodity", toolId: "qveris_finance.macro_commodity_benchmark", capability: "MACRO.COMMODITY.BENCHMARK", description: "原油、黄金等大宗商品基准价格", parameters: { commodity_name: "string?", symbol: "string?", start_date: "string?", end_date: "string?", frequency: "string?" }, returns: ["commodity_name", "symbol", "price", "change", "unit", "date"], coverage: "仅展示上游实际返回的基准价格；数据缺失时保持空态" },
  { kind: "trading_calendar", toolId: "cn_financial_pro.trade_dates.v1", provider: "cn_financial_pro", capability: "REF.EXCHANGE_CALENDAR", description: "按交易所查询真实交易日期，用于休市日门禁", parameters: { marketcode: "string", startdate: "string", enddate: "string" }, returns: ["time"] },
]);
