export const BUILTIN_CAPABILITIES = Object.freeze([
  { kind: "quote", toolId: "qveris_finance.mkt_l1_rt", capability: "MKT.L1.RT", description: "实时或近实时 Level 1 行情快照", parameters: { symbol: "string" }, returns: ["price", "change", "change_percent", "timestamp", "volume", "open", "high", "low", "previous_close"] },
  { kind: "details", toolId: "qveris_finance.ref_company_profile", capability: "REF.COMPANY_PROFILE", description: "上市公司基础概况与静态资料", parameters: { symbol: "string" }, returns: ["name", "exchange", "currency", "industry", "description", "market_cap"] },
  { kind: "fundamentals", toolId: "qveris_finance.fundamentals_derived_ratios", capability: "FUNDAMENTALS.DERIVED_RATIOS", description: "估值与盈利指标快照", parameters: { symbol: "string" }, returns: ["pe_ttm", "pb_ratio", "ps_ratio_ttm", "ev_to_ebitda", "dividend_yield", "as_of_date"] },
  { kind: "series", toolId: "qveris_finance.mkt_bars_eod", capability: "MKT.BARS.EOD", description: "历史日线 OHLCV 时间序列", parameters: { symbol: "string", start_date: "string", end_date: "string" }, returns: ["date", "open", "high", "low", "close", "volume"] },
  { kind: "core_event", toolId: "qveris_finance.event_calendar_corp", capability: "EVENT.CALENDAR.CORP", description: "上市公司分红、拆股、股东会等已排期事件", parameters: { symbol: "string", event_type: "string?", start_date: "string?", end_date: "string?" }, returns: ["date", "event_type", "description", "ratio"] },
  { kind: "capital_flow", toolId: "qveris_finance.flow_large_order", capability: "FLOW.LARGE_ORDER", description: "按订单规模拆分的个股资金流", parameters: { symbol: "string", start_date: "string?", end_date: "string?" }, returns: ["date", "super_large_net", "large_net", "medium_net", "small_net", "main_net"] },
  { kind: "sentiment", toolId: "qveris_finance.news_fin_tagged", capability: "NEWS.FIN.TAGGED", description: "带主题与情绪标签的财经新闻", parameters: { symbol: "string", start_date: "string?", end_date: "string?" }, returns: ["title", "url", "published_at", "source", "summary", "sentiment_label", "sentiment_score"] },
]);
