import { readFile } from "node:fs/promises";
const root = new URL("..", import.meta.url);
const load = (file) => readFile(new URL(file, root), "utf8");
const checks = [];
const check = (name, pass, detail) => checks.push({ name, pass, detail });

const [packageJson, cargoToml, tauriConfig, app, errorBoundary, stockWorkspace, marketChart, copilotPanel, marketViews, userState, userStateTransport, nativeUserState, workflow, prd, readme, watchlist, portfolioReview, briefingSchedule, hostIntegrationTest, localHost, developerPanel, styles, marketCalendar, desktopLifecycle, nativeMain, backgroundScheduler, anomalyAttribution] = await Promise.all([
  load("package.json").then(JSON.parse), load("src-tauri/Cargo.toml"), load("src-tauri/tauri.conf.json").then(JSON.parse),
  load("src/App.jsx"), load("src/components/AppErrorBoundary.jsx"), load("src/components/StockWorkspace.jsx"), load("src/components/MarketChart.jsx"), load("src/components/CopilotPanel.jsx"), load("src/components/SecondaryViews.jsx"), load("src/lib/userStateSchema.js"), load("src/lib/userState.js"), load("src-tauri/src/user_state.rs"), load(".github/workflows/release.yml"), load("docs/prd.md"), load("README.md"), load("src/lib/watchlist.js"), load("src/lib/portfolioReview.js"), load("src/lib/briefingSchedule.js"), load("scripts/local-host.integration.test.mjs"), load("scripts/local-host.mjs"), load("src/components/DeveloperPanel.jsx"), load("src/styles.css"), load("src-tauri/src/market_calendar.rs"), load("src-tauri/src/desktop_lifecycle.rs"), load("src-tauri/src/main.rs"), load("src-tauri/src/background_scheduler.rs"), load("src/lib/anomalyAttribution.js"),
]);
const version = packageJson.version;
check("版本号一致", cargoToml.includes(`version = "${version}"`) && tauriConfig.version === version, `当前 ${version}`);
check("真实数据边界", marketViews.includes("DATA_STATES") && marketViews.includes("realDataMode"), "页面必须显式区分未配置、加载、失败和空数据");
check("状态脱敏", userState.includes("normalizeUserState") && userState.includes("revision:") && userState.includes("watchlist:") && userState.includes("briefingSchedule:") && !userState.includes("integration-settings.json") && !userState.includes("apiKey"), "用户状态 schema 只处理脱敏用户事实");
check("发布资产", workflow.includes("SHA256SUMS") && workflow.includes("gh release upload"), "Release workflow 需校验并上传安装包");
check("安装升级路径", tauriConfig.bundle?.windows?.allowDowngrades === false && tauriConfig.bundle?.windows?.nsis?.installMode === "currentUser" && Boolean(tauriConfig.bundle?.windows?.wix?.upgradeCode) && readme.includes("不要求用户先手动卸载"), "Windows 同一产品必须覆盖升级、阻止降级并保留用户配置");
check("阶段设计", prd.includes("Stage 1E") && prd.includes("异动雷达"), "新功能必须先有可验收的 PRD 阶段设计");
check("自选迁移边界", watchlist.includes("parseWatchlistImport") && watchlist.includes("watchlistCsv"), "批量自选导入需先解析校验，导出不得包含实时数据或凭证");
check("复盘证据边界", portfolioReview.includes("createPortfolioReviewSnapshot") && portfolioReview.includes("if (!metrics.pricedCount)") && userState.includes("sanitizePortfolioReviews"), "盘后复盘只能由真实已计价持仓生成，并使用有界脱敏 schema");
check("自动复盘可靠性", app.includes("runDuePortfolioReview") && briefingSchedule.includes("retry-wait") && briefingSchedule.includes("hasFreshPortfolioQuote") && userState.includes("briefingSchedule"), "本地调度必须具备幂等、重试节流、当日真实行情门禁和持久化状态");
check("Local Host 公开契约", packageJson.scripts.test.includes("local-host.integration.test.mjs") && hostIntegrationTest.includes("RUNTIME_BUSY") && hostIntegrationTest.includes("invalid local host session") && hostIntegrationTest.includes("activeRequest"), "真实 HTTP 集成测试必须覆盖鉴权、持久化、并发互斥、取消和状态释放");
check("真实交易日门禁", briefingSchedule.includes("calendar-needed") && nativeUserState.includes("calendar_status") && marketCalendar.includes("REF.EXCHANGE_CALENDAR") && marketCalendar.includes("cn_financial_pro.trade_dates.v1"), "自动复盘必须先通过固定真实交易日历 CAP，失败时禁止猜测交易日");
check("桌面驻留生命周期", cargoToml.includes('features = ["tray-icon"]') && desktopLifecycle.includes("CloseAction::Hide") && desktopLifecycle.includes("foliomind_reconcile") && desktopLifecycle.includes("begin_cleanup") && nativeMain.includes("BackgroundScheduler") && nativeMain.includes("stop_and_join"), "主窗口关闭需隐藏到托盘，显式退出需幂等回收原生调度器、Web Host 与 Pi");
check("原生后台调度", backgroundScheduler.includes("market_calendar::fetch_trading_calendar") && backgroundScheduler.includes("user_state::mutate") && backgroundScheduler.includes("background-review-completed"), "桌面复盘必须由原生 worker 执行真实日历、行情门禁和原子幂等写入");
check("原生调度可观测性", backgroundScheduler.includes("background-scheduler-log") && backgroundScheduler.includes("duration_ms") && backgroundScheduler.includes("cost_from_value") && developerPanel.includes("desktopCostSummary"), "桌面调度调用必须提供脱敏日志、耗时和费用汇总");
check("用户状态并发控制", userState.includes("revision") && userStateTransport.includes("mergeUserStateChanges") && nativeUserState.includes("save_if_revision") && localHost.includes("USER_STATE_CONFLICT") && hostIntegrationTest.includes("USER_STATE_CONFLICT"), "Web、Local Host 与桌面必须以 revision/CAS 防止后台状态被旧页面覆盖");
check("CAP 能力工作台", developerPanel.includes("调用测试") && developerPanel.includes("参数 Schema") && developerPanel.includes("返回字段") && developerPanel.includes("刷新能力目录") && developerPanel.includes("完整能力目录") && developerPanel.includes("discoverCapabilities") && developerPanel.includes("capabilityToolSchema") && developerPanel.includes("复制 Tool Schema") && localHost.includes("BUILTIN_CAPABILITY_CATALOG") && localHost.includes("normalizeDiscoveredCapability") && localHost.includes("/api/dev/capabilities/discover") && styles.includes("min(1320px"), "开发面板必须提供大尺寸能力目录、稳定 schema、真实调用测试、动态目录和 Skill Tool 导出");
check("成本单位隔离", localHost.includes("qverisUnits") && localHost.includes("modelUnits") && developerPanel.includes("多单位"), "CAP 与模型网关费用必须按调用类型保留独立计费单位，未知费用不得估算");
check("自选列视图", marketViews.includes("MARKET_COLUMN_DEFINITIONS") && marketViews.includes("MARKET_COLUMNS_STORAGE_KEY") && marketViews.includes("恢复默认列") && styles.includes("--market-table-columns"), "市场页应支持非敏感、可恢复的自选行情列视图，并保持动态表格对齐");
check("命名行情视图", marketViews.includes("MARKET_VIEWS_STORAGE_KEY") && marketViews.includes("DEFAULT_MARKET_VIEWS") && marketViews.includes("CUSTOM_MARKET_VIEW_ID") && marketViews.includes(">= 10") && marketViews.includes("临时视图"), "命名行情视图只保存列偏好，手动修改进入临时视图并有数量上限");
check("异动证据解读", marketViews.includes("AnomalyAttribution") && anomalyAttribution.includes("buildAttributionPrompt") && anomalyAttribution.includes("evidenceIndex") && anomalyAttribution.includes("ANOMALY_ATTRIBUTION_DISCLAIMER") && anomalyAttribution.includes("https?"), "异动解读必须基于真实证据、引用来源、带免责声明并过滤不安全链接");
check("动态自选组盯盘", marketViews.includes("scope === \"watchlist\"") && marketViews.includes("lastSignalBySymbol") && userState.includes("lastSignalBySymbol") && prd.includes("Stage 2E 动态自选组盯盘"), "自选组规则必须动态展开当前标的、逐标的去重并通过状态 schema 脱敏迁移");
check("详情页快捷操作", stockWorkspace.includes('aria-label={isWatched ? "取消收藏" : "收藏"}') && stockWorkspace.includes('role="menuitem"') && stockWorkspace.includes("复制证券代码") && prd.includes("Stage 3V 股票详情快捷操作闭环"), "股票详情页收藏与更多菜单必须复用现有状态和可访问操作");
check("图表设置闭环", stockWorkspace.includes('aria-label="图表设置"') && stockWorkspace.includes("显示 MA5") && stockWorkspace.includes("显示网格线") && marketChart.includes("showMovingAverage") && marketChart.includes("showGrid") && marketChart.includes("movingAverage") && prd.includes("Stage 3W 行情图表设置闭环"), "图表设置只能改变显示层，MA5 必须基于真实序列计算");
check("对话快捷指令", copilotPanel.includes('aria-label="快捷指令"') && copilotPanel.includes('role="menuitem"') && copilotPanel.includes("最新行情") && copilotPanel.includes("chooseQuickPrompt") && prd.includes("Stage 3X 对话快捷指令闭环"), "快捷指令只编辑 draft，不绕过发送、取消和运行时互斥协议");
check("渲染故障恢复", app.includes("AppErrorBoundary") && errorBoundary.includes("页面暂时遇到问题") && errorBoundary.includes("重新加载应用") && prd.includes("Stage 3Y 渲染故障恢复"), "组件渲染异常必须显示安全恢复界面，不泄露异常正文或造成白屏");

const failed = checks.filter((item) => !item.pass);
console.log(JSON.stringify({ version, reviewedAt: new Date().toISOString(), checks, result: failed.length ? "needs-attention" : "pass" }, null, 2));
if (failed.length) process.exitCode = 1;
